### ISSUE TITLE
windows uart routines errors

### ISSUE THREAD

**Issue by moonglow** [dword1511/onewire-over-uart#1]
Hello and thanx for your project.
ReadFile and WriteFile will rise exeption becourse it cannot be used with lpNumberOfBytesRead equal to NULL. You can provide NULL pointer _ONLY_ if lpOverlapped is not NULL. You can check it with MSDN.

**Comment by dword1511** [comment]
This was fixed a year ago (commit 3cab7951cfda10ac581ea44e63464b41794ba251), however, I forgot to close the issue.
