### ISSUE TITLE
Linking error on linux

### ISSUE THREAD

**Issue by karczex** [dword1511/onewire-over-uart#3]
with -static option in makefile you get error: 

/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'digitemp_evil' failed
make: *** [digitemp_evil] Error 1

Tested on Fedora 25 with gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC)

**Comment by dword1511** [comment]
I have not used Fedora, but I guess you are missing glibc-devel, etc.

The Makefile does not invoke ld directly. Here is what it does on Debian:

```
$ make
gcc -c -Wall -O3 -o onewire.o onewire.c
gcc -c -Wall -O3 -o uart_posix.o uart_posix.c
gcc -c -Wall -O3 -o lsow.o lsow.c
gcc -static -O3 -o lsow onewire.o uart_posix.o lsow.o
gcc -c -Wall -O3 -o digitemp_evil.o digitemp_evil.c
gcc -c -Wall -O3 -o devices/common.o devices/common.c
gcc -c -Wall -O3 -o devices/ds18x20.o devices/ds18x20.c
gcc -static -O3 -o digitemp_evil onewire.o uart_posix.o digitemp_evil.o devices/common.o devices/ds18x20.o
```

**Comment by dword1511** [comment]
I have tried by myself and you need to install `glibc-static`.
